model: transformer

checkpoint: None

DATALOADER_CONFIG:
  DATA_DIR: /media/arthur/ExtremePro/public_datasets/Brains4Cars
  NUM_WORKERS: 4
  ACTIONS: ["end_action", "lchange", "lturn", "rchange", "rturn"]
  CAMERAS: ["road_camera", "face_camera"]
  # CAMERAS: ["face_camera"]
  USE_KFOLD: False

MODEL_CONFIG:
  EMBEDDING_LAYER:
    EMBEDDING_DIM:  32
  ENCODER_LAYER:
    MHA_HEADS:      2
    HIDDEN_DIM:     8
  TRANSFORMER:
    N_CLASSES:      5
    ENCODER_LAYERS: 6
    DECODER_LAYERS: 6
    MODEL_DIM:      256
    TOKEN_DIM:      128

# Model Training Configs
OPTIMIZATION:
  BATCH_SIZE_PER_GPU: 100 # 44gb
  NUM_EPOCHS: 100

  OPTIMIZER: adam_onecycle
  LR: 0.0001
  BETA1: 0.9
  BETA2: 0.999
  MOMENTUM: 0.9
  
  DECAY_RATE: 0.99
